name: Issues
on: pull_request

jobs:
  print_pr_title:
    runs-on: ubuntu-latest
    name: Print pull request title
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Print title
      shell: bash
      run: |
        echo "${{ github.event.pull_request.title }}"
