name: Issues
on:
  pull_request:
      branches:
      - main
jobs:
  print_pr_title:
    runs-on: ubuntu-latest
    name: Print pull request title
    
    steps:
    - name: Print title
      shell: bash
      run: |
        echo "${{ github.event.pull_request.title }}"
