name: Issues
on:
  pull_request:
      branches:
      - main
jobs:
  print_pr_title:
    runs-on: ubuntu-latest
    name: Print pull request title
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Print title
      shell: bash
      run: |
        echo "${{ github.event.pull_request.title }}"
