name: test-renovate
on:
  workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-22.04
    outputs:
      repo_list1: ${{ steps.Json-Splitter.outputs.json1 }}
      repo_list2: ${{ steps.Json-Splitter.outputs.json2 }}
    environment: renovate
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        # Don't waste time starting Renovate if JSON is invalid
      - name: Json-Splitter
        id: jsonSplitter
        run: |
          # Estrai il contenuto di repositories dal file json
          repositories=$(jq -r '.repositories[]' repo.json)
          
          # Conta il numero totale di elementi
          total=$(echo "$repositories" | wc -l)
          
          # Calcola il punto di divisione
          split=$(( (total + 1) / 2 ))
          
          # Dividi in due parti
          list1=$(echo "$repositories" | head -n "$split")
          list2=$(echo "$repositories" | tail -n +$((split + 1)))
          
          # Genera due file
          echo "$list1" >json1.json
          echo "$list2" >json2.json
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        # Don't waste time starting Renovate if JSON is invalid
      - name: step 2
        run: |
          ls




