name: test-renovate
on:
  workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-22.04
    environment: renovate
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        # Don't waste time starting Renovate if JSON is invalid
      - name: Json-Splitter
        id: jsonSplitter
        run: |
          # Estrai il contenuto di repositories dal file json
          repositories=$(jq -r '.repositories[]' repo.json)
          
          # Conta il numero totale di elementi
          total=$(echo "$repositories" | wc -l)
          
          # Calcola il punto di divisione
          split=$(( (total + 1) / 2 ))
          
          # Dividi in due parti
          list1=$(echo "$repositories" | head -n "$split")
          list2=$(echo "$repositories" | tail -n +$((split + 1)))
          
          # Crea il primo file json
          jq --argjson part1 "$(echo "$part1" | jq -Rsc 'split("\n")[:-1]')" \
             '.repositories = $part1' templateRepo.json > jsonRepo1.json
          
          # Crea il secondo file json
          jq --argjson part2 "$(echo "$part2" | jq -Rsc 'split("\n")[:-1]')" \
             '.repositories = $part2' templateRepo.json > jsonRepo2.json
          
  job2:
    runs-on: ubuntu-22.04
    needs: job1
    environment: renovate
    steps:
      - name: readFiles
        run: |
          ls




