name: test-renovate
on:
  workflow_dispatch
jobs:
  renovate:
    runs-on: ubuntu-22.04
    environment: renovate
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        # Don't waste time starting Renovate if JSON is invalid
      - name: Validate Renovate JSON
        run: |
              len=$(jq '.repositories[]' repo.json | wc -l)
              echo "$half/2"

